version: '2'

services:
  webpack:
    build: node
    environment: 
      - VIRTUAL_HOST=https://www.127.0.0.1.xip.io,www.127.0.0.1.xip.io
    expose:
      - 80
    volumes:
      - ./node/:/tmp/node
      - ./cpmteam.github.io/:/workspace
      - /var/lib/apt/lists/
      - /workspace/node_modules
    working_dir: /workspace
    command: /tmp/node/docker-up-image.sh

  couchdb:
    build: cpm-registry-couchapp
    ports:
      - 5984:5984
    environment: 
      - VIRTUAL_HOST=https://registry.127.0.0.1.xip.io,registry.127.0.0.1.xip.io
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes: 
      - couchdb-data:/data

  haproxy:
    # image: dockercloud/haproxy
    build: haproxy
    links:
      - webpack
      - couchdb
    environment: 
      - CERT_FOLDER=/certs/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/certs/
    ports:
      - 80:80
      - 443:443
      - 1936:1936

volumes:
   couchdb-data:
   certs:


