version: '2'

services:
  haproxy:
    # image: dockercloud/haproxy
    build: haproxy
    links:
      - web
      - couchdb
    environment: 
      - CERT_FOLDER=/certs/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/certs/
    ports:
      - 80:80
      - 443:443
      - 1936:1936

  web: 
    image: pierrezemb/gostatic
    expose:
      - 8043
    environment: 
      - VIRTUAL_HOST=https://www.127.0.0.1.xip.io,www.127.0.0.1.xip.io
    volumes: 
      - ./cpmteam.github.io/:/srv/http/
    command: --forceHTTP
  
  couchdb:
    build: cpm-registry-couchapp
    ports:
      - 5984:5984
    environment: 
      - VIRTUAL_HOST=https://registry.127.0.0.1.xip.io,registry.127.0.0.1.xip.io
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes: 
      - couchdb-data:/data

volumes:
   couchdb-data:
   certs:
