version: '2'

services:
  node:
#    image: node:7.7-slim
    image: jmfirth/webpack:7-slim
    container_name: cpmteamdevenv_node
    ports:
      - 8800:8080
    environment: 
      - VIRTUAL_HOST=https://www.127.0.0.1.xip.io,www.127.0.0.1.xip.io
    volumes:
      - .npm-cache:/tmp/npm-cache
      - .yarn-cache:/tmp/yarn-cache
      - ./node/:/tmp/node
      - ./apt-cache:/var/lib/apt/lists/
      - ./cpmteam.github.io/:/workspace
    working_dir: /workspace
    command: /tmp/node/docker-build-image.sh

  couchdb:
    build: cpm-registry-couchapp
    ports:
      - 5984:5984
    environment: 
      - VIRTUAL_HOST=https://registry.127.0.0.1.xip.io,registry.127.0.0.1.xip.io
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes: 
      - couchdb-data:/data

volumes:
   couchdb-data:
