version: '2'

services:
  haproxy:
    image: dockercloud/haproxy
    links:
      - web
      - couchdb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
      - 1936:1936

  web: 
    image: pierrezemb/gostatic
    expose:
      - 8043
    ports:
      - 8043:8043
    environment: 
      - VIRTUAL_HOST=*
    volumes: 
      - ./cpmteam.github.io/:/srv/http/
    command: --forceHTTP
  
  couchdb:
    build: cpm-registry-couchapp
    environment: 
      - VIRTUAL_HOST=registry.127.0.0.1.xip.io
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes: 
      - couchdb-data:/data

volumes:
   couchdb-data:
